services:
  db:
    image: postgres:15 
    container_name: project3_db
    restart: always
    environment:
      POSTGRES_USER: user 
      POSTGRES_PASSWORD: password 
      POSTGRES_DB: projectdb 
    volumes:
      - ./database:/docker-entrypoint-initdb.d 
      - postgres_data:/var/lib/postgresql/data 
    ports:
      - "5434:5432" 

  app:
    container_name: project_app
    build: .
    ports:
      - "8502:8501"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: projectdb 
      DB_USER: user 
      DB_PASSWORD: password
    volumes:
      - .:/app

volumes:
  postgres_data: